[versions]
kotlinStdlibJdk7Version = "1.9.10"
androidXCoreVersion = "1.12.0"
appcompatVersion = "1.6.1"
preferenceVersion = "1.2.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidXCoreVersion" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceVersion" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdlibJdk7Version" }

[plugins]

