[versions]
kotlinVersion = "2.1.20"
# AndroidX Core
androidXCoreVersion = "1.16.0"
appcompatVersion = "1.7.0"
preferenceVersion = "1.2.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidXCoreVersion" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceVersion" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinVersion" }

[plugins]

